In [10]:
import numpy as np

In [12]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [15]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print (b)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
b[0,1:3]
b[0:1,2]

array([3])